### ISSUE TITLE
Where to enter the school name etcetera?

### ISSUE THREAD

**Issue by Griesenb** [JochemVanIterson/DavUntis#3]
Wanted to test your promising project, but could not log in with my data.
There should probable be a webuntis server and school name be defined somewhere.

**Comment by JochemVanIterson** [comment]
Hi, you can log in to the admin page using your two hashtags (##) plus the username you defined during installation. Under the Untis Settings tab you can set your Untis server and school settings.

**Comment by Griesenb** [comment]
Hi, thanks for the quick answer.

Maybe I did the installation the wrong way. I just uploaded the files to a folder on my test site and entered the /install/ where I did fill out the data for the DB and the script created a _Users table with my user "test".
After that I visited the folder and the DavUntis page asks me for clicking on Login.

Did you expect my idea of an installation or is there the error?

I tried to put the ##test after the URL and as a username during the login both without any results.

**Comment by JochemVanIterson** [comment]
Hmmm, I will check the installation script. It is possible that not all the sql tables are created during install.

**Comment by JochemVanIterson** [comment]
I've updated the install script so that is creates all the necessary sql tables. If you rerun the install script they should be initialized. (You may have to remove your previously created tables)

**Comment by Griesenb** [comment]
Thanks, the installer is working now and creates (probably) all tables.

The admin dashboard is opening now.

The format for entering the "Server url" is (for the ones interested) without "https://" and "/WebUntis/" like this: greekmythology.webuntis.com
